### ISSUE TITLE
Suggestion: About the cannonball launching

### ISSUE THREAD

**Issue by LoneWolfHT** [archfan7411/minetest-cannon#2]
It's possible to make the cannon node fire in the direction it's facing. `node.param2` holds the direction the node is facing. It can be turned into a vector with this:
```lua
local function param2_to_dir(param2)
	if param2 == 0 then
		return({x=0, y=0, z=1})
	elseif param2 == 1 then
		return({x=1, y=0, z=0})
	elseif param2 == 2 then
		return({x=0, y=0, z=-1})
	elseif param2 == 3 then
		return({x=-1, y=0, z=0})
	else
		return({x=0, y=0, z=0})
	end
end```

**Comment by archfan7411** [comment]
Good idea, but this mod is aimed for CTF-style games, where the cannon will be used against both players and structures.

Would it be possible to have a 45-degree aiming range instead, like this?
![cannon_aim](https://user-images.githubusercontent.com/33993466/47569130-e3361580-d900-11e8-80aa-28cff2cc41da.PNG)

**Comment by LoneWolfHT** [comment]
Could probably do that. I'm not yet sure how I would to the calculations to limit the firing range though. To choose which direction the cannon will fire you could set it up so that the cannon's firing direction will be set to the player's look direction
If you gave the cannon ball a random x and y velocity of -1 to 1 (Or -3 to 3) that might make it a little more realistic accuracy wise.

**Comment by archfan7411** [comment]
I like the idea of random velocities. Will add (though for gameplay's sake, the amount will be rather small.)
